import streamlit as st
from transformers import pipeline

# Load the model with error handling and optimized settings
try:
    generator = pipeline("text-generation", model="distilgpt2", device=-1, framework="pt")
except Exception as e:
    st.error(f"Error loading model: {str(e)}")
    st.stop()

# Load training data
try:
    with open("training_data.txt", "r", encoding="utf-8") as f:
        training_data = f.read()
except FileNotFoundError:
    st.error("training_data.txt not found. Please ensure it's in the repository.")
    st.stop()

# Streamlit app
st.title("Property Management AI")
st.write("Ask questions or request assistance with property management tasks.")

# User input
user_input = st.text_area("Enter your query", "Draft an email to a leaseholder requesting payment for overdue service charges.")

if st.button("Submit"):
    # Construct the prompt
    system_prompt = """You are a property management AI assistant. Use the following examples to guide your responses:\n\n"""
    system_prompt += training_data
    full_prompt = f"{system_prompt}\n\nUser Query: {user_input}\n\nAssistant Response: "
    
    # Generate response with error handling and debugging
    try:
        # Debug: Show input prompt length
        st.write(f"Prompt length: {len(full_prompt)} characters")
        
        response = generator(full_prompt, max_new_tokens=150, num_return_sequences=1, truncation=True)
        
        # Debug: Show raw response
        st.write("Raw Response:", response)
        
        if not response or len(response) == 0:
            st.error("No response generated by the model.")
            st.stop()
        
        generated_text = response[0].get("generated_text", "")
        if not generated_text:
            st.error("Generated text is empty.")
            st.stop()
        
        # Extract response
        response_start = generated_text[len(full_prompt):].strip()
        if not response_start:
            response_start = "No response generated. Please try rephrasing your query."
        
        # Display response
        st.write("**Response:**")
        st.write(response_start)
    except Exception as e:
        st.error(f"Error generating response: {str(e)}")
